### ISSUE TITLE
Ready Player Me integration in android application

### ISSUE THREAD

**Issue by vrushalipandit** [readyplayerme/Example-Android-Kotlin#3]
During integration of the Ready Player Me Avatar in android application, I followed the steps given in documentation (https://docs.readyplayer.me/integration-guides/android-native). But the steps which are given in the documentation are not clearly specified.

Only the first step in the documentation is clear and able to develop. That means I’m able to only redirect the user to the partner domain where user can create the avatar but not able to retrieve the Avatar URL to the app side. So we can use the URL as per our requirements.

So, can you please help me with how to retrieve the Avatar URL to the app side.

**Comment by duybuikardiachain** [comment]
Same issue here

**Comment by srcnalt** [comment]
There is a PR dor the updates on this here #5
Now you will be able to receive the URL in the `WebViewInterface.kt` and once it's received you can use it.
